/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b6c8e4",
        "primary-fixed": "#d4e3ff",
        "background": "#fff8f3",
        "secondary-container": "#e0e0db",
        "error-container": "#ffdad6",
        "on-surface": "#201b13",
        "on-primary-fixed-variant": "#374860",
        "on-background": "#201b13",
        "inverse-on-surface": "#fbefe1",
        "inverse-surface": "#362f26",
        "on-surface-variant": "#44474d",
        "on-tertiary-fixed-variant": "#713700",
        "on-secondary-fixed": "#1a1c19",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface": "#fff8f3",
        "primary": "#000919",
        "secondary-fixed": "#e3e3de",
        "surface-container": "#f8ecde",
        "primary-fixed-dim": "#b6c8e4",
        "on-primary-fixed": "#091c32",
        "error": "#ba1a1a",
        "surface-tint": "#4f5f78",
        "on-secondary-fixed-variant": "#454744",
        "on-error": "#ffffff",
        "surface-container-high": "#f2e6d9",
        "secondary-fixed-dim": "#c6c7c2",
        "tertiary-container": "#371800",
        "surface-dim": "#e4d8cb",
        "on-secondary": "#ffffff",
        "outline": "#74777d",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#d06d0d",
        "surface-variant": "#ece1d3",
        "primary-container": "#0f2137",
        "tertiary-fixed-dim": "#ffb783",
        "on-secondary-container": "#62635f",
        "on-tertiary-fixed": "#301400",
        "secondary": "#5d5f5b",
        "surface-container-low": "#fef2e4",
        "surface-bright": "#fff8f3",
        "on-tertiary": "#ffffff",
        "tertiary": "#140500",
        "outline-variant": "#c4c6cd",
        "on-primary-container": "#7889a4",
        "tertiary-fixed": "#ffdcc5",
        "surface-container-highest": "#ece1d3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "stack-lg": "48px",
        "container-max": "1200px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "stack-md": "24px",
        "gutter": "24px",
        "stack-sm": "12px"
      },
      fontFamily: {
        "caption": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-md": ["'Source Serif 4'", "serif"],
        "display-lg": ["'Source Serif 4'", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["'Source Serif 4'", "serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-lg": ["'Source Serif 4'", "serif"],
        "serif": ["'Source Serif 4'", "serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-md": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
